### ISSUE TITLE
Correções no gitpages pós Unidade 1

### ISSUE THREAD

**Issue by l-ricardo** [mdsreq-fga-unb/2023.1-UnBnoFluxo#16]
Descrição das alterações pedidas depois da primeira entrega.
Obs.: As marcadas como feito estão no dev

- [x] **Adicionar Scrum no Processo de Desenvolvimento de Software**
- [x] **Substituir diagrama Scrum pelo novo do ScrumXP**
- [x] **Colocar diagrama ScrumXP no Processo de Desenvolvimento de Software**
- [x] **Remover diagrama sem sentido do Processo de Desenvolvimento de Software**
- [x] **Programação em pares é obrigatória**
- [x] **Refazer completamente Planejamento das Fases e/ou Iterações do Projeto**
- [x] **Revisitar Matriz de Comunicação**
- [x] **Refazer completamente critérios de Replanejamento**
- [x] **Colocar professor como cliente**
- [x] **Arrumar segundo novo cliente**
- [x] **Refazer Objetivos do Produto sem adjetivos**
- [x] **Fazer Declaração de Posição do Produto em tabela**
- [x] **Historico de Revisão é um pra cada página?**
- [x] **Reformular DoD adicionando mais critérios**
- [x] **Checar DoR "Ordenados valor de negócio"**
- [x] **Priorizar backlog**
- [x] **Disponibilizar backlog fora do pages**
- [x] **Dividir em tema, epico e US. nessa ordem**
- [x]  **Fazer outra tabela com id das US com declarações afim de fazer os criterios de aceitaçao**
- [x] **Pegar as 14 US com maior pontuação e registrar critérios de aceitação**
- [x] **Dev Master: Preencher relatórios das sprint 3 e 4**
- [x] **Dev Teste: Definir workflow do gitactions**
- [x] **Devs Back: Refazer arquitetura do back**
- [x] **Reformular os CA em afirmativas**
- [x] **Atualizar visão geral do projeto**
- [x] **Fazer video de apresentaçao**
- [x] **Rever os CAs US09: "para todos os dados", quais dados?**
- [x] **Rever os CAs US09: "corretamente preenchidos", especificar cada um como é estar corretamente preenchido, string? num de caracteres? regex?**
- [x] **Rever os CAs US04: "CAs fracos"**
- [x] **Colocar mais de 1 CA nas US11, US02 e US03**
- [x] **CAs da US08: Onde estão / da onde vem / quais sao esses limites estabelecidos pela faculdade**
- [x] **US07 ta tao ruim que ele nem criticou direito kkk ;(**
- [x] **Checar MVP1 e MVP2. US com nomes e numeros corretos? Alguma US nova e com alta prioridade ficou de fora?**
- [x] **Atualizar o github projects com as US e CAs atualizados. Também colocar o link na planilia e no pages**

**Comment by jvcostta** [comment]
disponibilizar backlog fora do pages

**Comment by jvcostta** [comment]
- [ ] disponibilizar backlog fora do pages
- [ ] priorizar backlog
- [ ] dividir em tema, epico e US. nessa ordem
- [ ] fazer outra tabela com id das US com declarações afim de fazer os criterios de aceitaçao
- [ ] pegar as 14 US com maior pontuação e registrar critérios de aceitação

**Comment by l-ricardo** [comment]
- [ ] Refazer arquitetura do back

**Comment by jvcostta** [comment]
- [ ]  Reformular os CA em afirmativas
- [ ] Dev Master: Preencher relatórios das sprint 3 e 4.
- [ ] atualizar visão geral do projeto
- [ ] Dev Teste: Definir workflow do gitactions
- [ ] fazer video de apresentaçao
- [ ] fazer ajustes nas US comentados pelo professor
